force-app/main/default/objects/Agent__c/Agent__c.object-meta.xml
<CustomObject>
    <label>Agent</label>
    <nameField>
        <displayFormat>AG-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agent__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment_Name__c/Appointment_Name__c.object-meta.xml
<CustomObject>
    <label>Appointment Name</label>
    <nameField>
        <label>Appointment Name Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppointmentNames</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment_Name__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AppointmentNames</relationshipLabel>
    <relationshipName>AppointmentNames</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_Name__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <label>Agent</label>
    <referenceTo>Agent__c</referenceTo>
    <relationshipLabel>AppointmentNames</relationshipLabel>
    <relationshipName>AppointmentNames</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment_Name__c/fields/Communication_method__c.field-meta.xml
<CustomField>
    <fullName>Communication_method__c</fullName>
    <label>Communication method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Face to Face</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>What&apos;s App</fullName>
            </value>
            <value>
                <fullName>Zoom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment_Name__c/fields/Schedule_setup__c.field-meta.xml
<CustomField>
    <fullName>Schedule_setup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule setup</label>
    <referenceTo>Schedule_setup__c</referenceTo>
    <relationshipLabel>AppointmentNames</relationshipLabel>
    <relationshipName>AppointmentNames</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_Name__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule_setup__c/Schedule_setup__c.object-meta.xml
<CustomObject>
    <label>Schedule setup</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Schedule setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_setup__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>Agent__c</referenceTo>
    <relationshipLabel>Schedule setups</relationshipLabel>
    <relationshipName>Schedule_setups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule_setup__c/fields/Close_date__c.field-meta.xml
<CustomField>
    <fullName>Close_date__c</fullName>
    <label>Close date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule_setup__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Schedule_setup__c/fields/Next_Appointment_date__c.field-meta.xml
<CustomField>
    <fullName>Next_Appointment_date__c</fullName>
    <label>Next Appointment date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule_setup__c/fields/Recurrence__c.field-meta.xml
<CustomField>
    <fullName>Recurrence__c</fullName>
    <label>Recurrence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
                <default>true</default>
                <label>One Time</label>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule_setup__c/fields/Start_time__c.field-meta.xml
<CustomField>
    <fullName>Start_time__c</fullName>
    <label>Start time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Schedule_setup__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BookingBatchHelper.cls
public with sharing class BookingBatchHelper
{
    
    public BookingBatchHelper(List<Schedule_setup__c> scList)
    {
        for (Schedule_setup__c sc : scList)
        {
            if(sc.Recurrence__c=='One Time'){
                try{
                    Appointment_Name__c sobj = new Appointment_Name__c(
                        Name = sc.Next_Appointment_date__c+' : '+sc.Start_time__c+' to '+sc.End_Time__c,                            
                        Agent__c = sc.Agent__c,                  
                        //?  Account__c = 'undefined',                
                        Status__c = 'Available',                 
                        //? Communication_method__c = 'Face to Face',  
                        Schedule_setup__c = sc.Id,           
                        Date__c = sc.Next_Appointment_date__c,      
                        Start_time__c = sc.Start_time__c,             
                        End_Time__c = sc.End_Time__c               
                      );
                      insert sobj;
                      sc.status__c='Closed';
                    update sc;
                }catch (System.DmlException e) 
                {
                     System.debug('we caught a dml exception: ' + e.getDmlMessage(0));
                }
            }
            if(sc.Recurrence__c=='Daily'&&(sc.Next_Appointment_date__c.daysBetween(date.today())<15||sc.Start_date__c==sc.Next_Appointment_date__c)){
                try{
                    //create Daily to 30 as limitation
                    Integer nOfDays=30;
                    if(sc.Close_date__c!=null){

                         nOfDays=sc.Next_Appointment_date__c.daysBetween(sc.Close_date__c);
                         if (nOfDays>30) {
                            nOfDays=30;
                         }
                    }
                    List<Appointment_Name__c> appointmentList= new List<Appointment_Name__c>();
                    Date nextDate=sc.Next_Appointment_date__c;
                    for(Integer cnt=0;cnt<nOfDays&&nextDate<=sc.Close_date__c;cnt++){
                        Appointment_Name__c sobj = new Appointment_Name__c(
                            Name =nextDate+' : '+sc.Start_time__c+' to '+sc.End_Time__c,                            
                            Agent__c = sc.Agent__c,                  
                            //?  Account__c = 'undefined',                
                            Status__c = 'Available',                 
                            //? Communication_method__c = 'Face to Face',  
                            Schedule_setup__c = sc.Id,           
                            Date__c = nextDate,      
                            Start_time__c = sc.Start_time__c,             
                            End_Time__c = sc.End_Time__c               
                        );
                        nextDate.addDays(1);
                        appointmentList.add(sobj);
                    }
                    insert appointmentList; 
                    sc.Next_Appointment_date__c=nextDate;
                    if(sc.Close_date__c!=null&& nextDate>sc.Close_date__c)sc.status__c='Closed';
                    update sc;
                }catch (System.DmlException e) 
                {
                     System.debug('we caught a dml exception: ' + e.getDmlMessage(0));
                }
            }
            if(sc.Recurrence__c=='Weekly'&&(sc.Next_Appointment_date__c.daysBetween(date.today())<15||sc.Start_date__c==sc.Next_Appointment_date__c)){
                try{
                    //create week to Month as limitation
                    Integer nOfWeeks=4;
                    if(sc.Close_date__c!=null){
                        nOfWeeks=sc.Next_Appointment_date__c.daysBetween(sc.Close_date__c);
                        if (nOfWeeks>4) {
                        nOfWeeks=4;
                        }
                    }
                    List<Appointment_Name__c> appointmentList= new List<Appointment_Name__c>();
                    Date nextDate=sc.Next_Appointment_date__c;
                    for(Integer cnt=0;cnt<nOfWeeks&&nextDate<=sc.Close_date__c;cnt++){
                        Appointment_Name__c sobj = new Appointment_Name__c(
                            Name =nextDate+' : '+sc.Start_time__c+' to '+sc.End_Time__c,                            
                            Agent__c = sc.Agent__c,                  
                            //?  Account__c = 'undefined',                
                            Status__c = 'Available',                 
                            //? Communication_method__c = 'Face to Face',  
                            Schedule_setup__c = sc.Id,           
                            Date__c = nextDate,      
                            Start_time__c = sc.Start_time__c,             
                            End_Time__c = sc.End_Time__c               
                        );
                        nextDate.addDays(7);
                        appointmentList.add(sobj);
                    }
                    insert appointmentList; 
                    sc.Next_Appointment_date__c=nextDate;
                    if(sc.Close_date__c!=null&& nextDate>sc.Close_date__c)sc.status__c='Closed';
                    update sc;
                }catch (System.DmlException e) 
                {
                     System.debug('we caught a dml exception: ' + e.getDmlMessage(0));
                }
            }
            if(sc.Recurrence__c=='Monthly'&&(sc.Next_Appointment_date__c.daysBetween(date.today())<15||sc.Start_date__c==sc.Next_Appointment_date__c)){
                try{Date nextDate=sc.Next_Appointment_date__c;
                    Appointment_Name__c sobj = new Appointment_Name__c(
                            Name =nextDate+' : '+sc.Start_time__c+' to '+sc.End_Time__c,                            
                            Agent__c = sc.Agent__c,                  
                            //?  Account__c = 'undefined',                
                            Status__c = 'Available',                 
                            //? Communication_method__c = 'Face to Face',  
                            Schedule_setup__c = sc.Id,           
                            Date__c = nextDate,      
                            Start_time__c = sc.Start_time__c,             
                            End_Time__c = sc.End_Time__c               
                        );
                        nextDate.addMonths(1);
                        insert sobj; 
                        sc.Next_Appointment_date__c=nextDate;
                        if(sc.Close_date__c!=null&& nextDate>sc.Close_date__c)sc.status__c='Closed';
                        update sc;
                    
                    
                }catch (System.DmlException e) 
                {
                     System.debug('we caught a dml exception: ' + e.getDmlMessage(0));
                }
            }
        }
    }

   
}