force-app/main/default/objects/Agent__c/Agent__c.object-meta.xml
<CustomObject>
    <label>Agent</label>
    <nameField>
        <displayFormat>AG-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agent__c/fields/Agent_name__c.field-meta.xml
<CustomField>
    <fullName>Agent_name__c</fullName>
    <label>Agent name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agent__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment_Name__c/Appointment_Name__c.object-meta.xml
<CustomObject>
    <label>Appointment Name</label>
    <nameField>
        <label>Appointment Name Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppointmentNames</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment_Name__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AppointmentNames</relationshipLabel>
    <relationshipName>AppointmentNames</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_Name__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <label>Agent</label>
    <referenceTo>Agent__c</referenceTo>
    <relationshipLabel>AppointmentNames</relationshipLabel>
    <relationshipName>AppointmentNames</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment_Name__c/fields/Communication_method__c.field-meta.xml
<CustomField>
    <fullName>Communication_method__c</fullName>
    <label>Communication method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Face to Face</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>What&apos;s App</fullName>
            </value>
            <value>
                <fullName>Zoom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment_Name__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BookingLwcController.cls
public with sharing class BookingLwcController {
    /// send email and update appointment
    @AuraEnabled
    public static void bookAppointment(Id appointmentID ,Id customer,String communicationMethod) {
        try {
            Appointment_Name__c appointment = new Appointment_Name__c();
                
            // get all expired cim card (Constituent/org) who has donation upcoming in next months of type credit card ()
            appointment = [
                SELECT Id, Account__c, Communication_method__c,Status__c,Account__r.Name ,Date__c,Agent__r.Agent_name__c
                  FROM Appointment_Name__c 
                WHERE Id =:appointmentID Limit 1
            ];
            if(appointment==null){
                throw new AuraHandledException('no appointment');
            }
            appointment.Account__c=customer ;
            appointment.Communication_method__c=communicationMethod;
            appointment.Status__c='Booked' ;
            update appointment;
            sendEmail(appointment);
            
        } catch (Exception err) {
            throw new AuraHandledException(err.getMessage());
        }
    }
    static void sendEmail (Appointment_Name__c appointment)
    {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'mwissa@copticorphans.org'};
        mail.setToAddresses(toAddresses);
        mail.setSenderDisplayName('Task Booked Salesforce Automation');
        mail.setSubject('Taask Finish : Booked Appointment');
        mail.setUseSignature(false);
        mail.setPlainTextBody('  Booked Appointment has been Finished ,his ID = '+appointment.Id +' between '+appointment.Account__r.Name +' and '+appointment.Agent__r.Agent_name__c +' at day '+appointment.Date__c +' \n----------------------------------------------------\n* Job: \n    ' 
                           
                              );
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}