force-app/main/default/objects/Agent__c/Agent__c.object-meta.xml
<CustomObject>
    <label>Agent</label>
    <nameField>
        <displayFormat>AG-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agent__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule_setup__c/Schedule_setup__c.object-meta.xml
<CustomObject>
    <label>Schedule setup</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Schedule setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_setup__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>Agent__c</referenceTo>
    <relationshipLabel>Schedule setups</relationshipLabel>
    <relationshipName>Schedule_setups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule_setup__c/fields/Close_date__c.field-meta.xml
<CustomField>
    <fullName>Close_date__c</fullName>
    <label>Close date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule_setup__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Schedule_setup__c/fields/Next_Appointment_date__c.field-meta.xml
<CustomField>
    <fullName>Next_Appointment_date__c</fullName>
    <label>Next Appointment date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule_setup__c/fields/Recurrence__c.field-meta.xml
<CustomField>
    <fullName>Recurrence__c</fullName>
    <label>Recurrence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
                <default>true</default>
                <label>One Time</label>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule_setup__c/fields/Start_time__c.field-meta.xml
<CustomField>
    <fullName>Start_time__c</fullName>
    <label>Start time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Schedule_setup__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BookingBatch.cls
global class BookingBatch implements Database.Batchable<sObject>, Database.Stateful {
    // instance member to retain state across transactions   
    global Iterable<sObject> start(Database.BatchableContext bc)
    {
        System.debug('Begining of Start Method');
        
        // Date today;
        // if (Test.isRunningTest()){
        //     today = Date.newInstance(2023, 03, 20);
        // } else{
        //     today = Date.today();
        // }
        List<Schedule_setup__c> scList = new List<Schedule_setup__c>();
        
        // get all expired cim card (Constituent/org) who has donation upcoming in next months of type credit card ()
        scList = [
            SELECT Id, Agent__c,status__c, Recurrence__c, Start_date__c,
            Next_Appointment_date__c, Close_date__c, End_Time__c, Start_time__c FROM Schedule_setup__c
            where status__c='Open'
            
        ]; 
       
        return scList;      
    }

    global void execute(Database.BatchableContext bc, List<Schedule_setup__c> scope)
    {
        System.debug('# BookingBatch - execute - * Started');
        //call About Expire Batch Helper Class
        BookingBatchHelper BookingBatchHelper = New BookingBatchHelper(scope);
    }

    //finish Method Call Send Email to Support
    global void finish(Database.BatchableContext bc)
    {
        System.debug('# BookingBatch - finish - * Started');

        //Select Batch Job Data
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
        System.debug('finish Method - jobs : '+job);

        // call send email Method
        
        if (Test.isRunningTest()){
            sendEmail(job);
        }
        else if (job.NumberOfErrors>0)
        {sendEmail(job);}
    }    

    //Send Email Method to Support
    private void sendEmail (AsyncApexJob job)
    {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'mwissa@copticorphans.org'};
        mail.setToAddresses(toAddresses);
        mail.setSenderDisplayName('Task Salesforce Automation');
        mail.setSubject('Batch Finish : BookingBatch');
        mail.setUseSignature(false);
        mail.setPlainTextBody('  BookingBatch has been Finished.\n----------------------------------------------------\n* Job: \n    ' 
                              + job
                              );
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}